server:
  port: 5000

spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: bob_cody

#  boot:
#    admin:
#      client:
#        instance:
#          name: Bob Cody Application
#          metadata:
#            user:
#              name: monitor
#              password: passwordTest
#        url: http://localhost:8010
#        username: admin
#        password: Nr4Kd7

db:
  jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bob_cody
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  maximum-pool-size: 30
  initialization-mode: always
  minimum-idle: 5
  connection-timeout: 30000

logging:
  level:
    org:
      springframework:
        web:
          HttpLogging: info
        client: info
      hibernate:
        SQL:
          DEBUG
        type:
          TRACE
    root: info

#  cache:
#    jcache:
#      config: ehcache.xml

## spring boot admin
#management:
#  endpoints:
#    web:
#      exposure:
#        include: .*
#      base-path: /actuator
#    health:
#      show-details: always




bot:
  web-hook-path: значение
  bot-name: имя
  bot-token: токен
  #  bot-name: BobCodyBot
  #  bot-token: 1172306859:AAEKAeABtE0sUjNm5rumQhFEEwLcT5wQ-us  #бобби
  web-hook:
    reload-on-startup: true   # обновлять или нет веб-хук при старте приложения

admin-chat-id: 445682905
moderator-chat-id: 445682905
#     API
fga:
  random-advice-url: https://fucking-great-advice.ru/api/random

sber:
  rate:
    url: https://www.cbr.ru/scripts/XML_daily.asp

pie-url: https://poetory.ru/

weather:
  api:
    url: https://api.openweathermap.org/data/2.5/forecast
    key: ключ

elk:
  path: CgACAgIAAxkBAAIZjGPlVnwFpHfwkOeWJ8dIyHhLs9ixAAI2EwACR_tRSUjfCe0K0Dn8LgQ

timer:
  elk:
    enabled: true
    cron: 0 59 17 * * FRI
    chat: 445682905  #todo в перспективе сделать через БД