server:
  port: 5000

spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: bob_cody

db:
  jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bob_cody
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  maximum-pool-size: 30
  initialization-mode: always
  minimum-idle: 5
  connection-timeout: 30000

logging:
  level:
    org:
      springframework:
        web:
          HttpLogging: info
        client: info
      hibernate:
        SQL:
          DEBUG
        type:
          TRACE
    root: info

bot:
  web-hook-path: значение
  bot-name: имя
  bot-token: токен
  #  bot-name: BobCodyBot
  #  bot-token: 1172306859:AAEKAeABtE0sUjNm5rumQhFEEwLcT5wQ-us  #бобби
  web-hook:
    reload-on-startup: true   # обновлять или нет веб-хук при старте приложения
  maintenance-mode: false
  admin-chat-id: 445682905
  moderator-chat-id: 445682905
  ignore-list: 12345

thirdparty-api:
  fga:
    random-advice-url: https://fucking-great-advice.ru/api/random
  sber:
    rate:
      url: https://www.cbr.ru/scripts/XML_daily.asp
  weather:
    api:
      url: https://api.openweathermap.org/data/2.5/forecast
      key: 88da851375b3a80f6b0d65e55bfc2e37
  pie-url: https://poetory.ru/

timer:
  elk:
    enabled: true
    cron: 0 59 17 * * FRI
    chat: 445682905  #todo в перспективе сделать через БД
  pie:
    enabled: true
    cron: 0 0/5 * * * ?

elk:
  path: CgACAgIAAxkBAAIZjGPlVnwFpHfwkOeWJ8dIyHhLs9ixAAI2EwACR_tRSUjfCe0K0Dn8LgQ
